import { useEffect, useState } from "react";
import { ArrowLeft, Wallet, Sparkles, TrendingUp } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../api/axios";
import { InsightResponse, PredictionResult, CategoryForecast, AnomalyResult } from "../types/finance";

export default function Insights() {
  const [insight, setInsight] = useState<InsightResponse | null>(null);
  const [prediction, setPrediction] = useState<PredictionResult | null>(null);
  const [forecasts, setForecasts] = useState<CategoryForecast[]>([]);
  const [anomalies, setAnomalies] = useState<AnomalyResult[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [predictionError, setPredictionError] = useState<string | null>(null);

  useEffect(() => {
    api
      .get("/insights")
      .then((res) => setInsight(res.data.data))
      .catch(() => {})
      .finally(() => setIsLoading(false));

    api
      .get("/predictions/monthly")
      .then((res) => setPrediction(res.data.data))
      .catch((err) => setPredictionError(err?.response?.data?.message || null));

    api
      .get("/predictions/categories")
      .then((res) => setForecasts(res.data.data))
      .catch(() => {});

    api
      .get("/predictions/anomalies")
      .then((res) => setAnomalies(res.data.data.anomalies))
      .catch(() => {});
  }, []);

  return (
    <div className="min-h-screen bg-slate-50">
      <header className="border-b border-slate-200 bg-white px-6 py-4">
        <div className="mx-auto flex max-w-4xl items-center gap-3">
          <Link to="/dashboard" className="rounded-lg p-1.5 text-ink-500 hover:bg-slate-100">
            <ArrowLeft className="h-4 w-4" />
          </Link>
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-500">
            <Wallet className="h-4 w-4 text-white" />
          </div>
          <span className="font-semibold text-ink-900">AI Insights</span>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-8 space-y-6">
        <div className="rounded-2xl border border-slate-200 bg-white p-5">
          <div className="flex items-center gap-2 text-ink-700">
            <Sparkles className="h-4 w-4 text-brand-500" />
            <span className="text-sm font-medium">This month, explained</span>
          </div>
          {isLoading ? (
            <div className="mt-3 h-16 animate-pulse rounded-lg bg-slate-100" />
          ) : insight ? (
            <>
              <p className="mt-3 text-sm text-ink-700">{insight.explanation}</p>
              <p className="mt-2 text-xs text-ink-400">
                {insight.generatedBy === "ai" ? "Generated by AI from your verified data" : "Generated from your verified data"}
              </p>
            </>
          ) : (
            <p className="mt-3 text-sm text-ink-500">Add a few expenses to see insights here.</p>
          )}
        </div>

        <div className="rounded-2xl border border-slate-200 bg-white p-5">
          <div className="flex items-center gap-2 text-ink-700">
            <TrendingUp className="h-4 w-4 text-brand-500" />
            <span className="text-sm font-medium">Spending forecast</span>
          </div>
          {predictionError ? (
            <p className="mt-3 text-sm text-ink-500">{predictionError}</p>
          ) : prediction ? (
            <>
              <p className="mt-3 text-2xl font-semibold text-ink-900">
                ₹{prediction.predictedAmount.toLocaleString("en-IN")}
              </p>
              <p className="text-xs text-ink-500">
                Likely range: ₹{prediction.confidenceRange.lower.toLocaleString("en-IN")} – ₹
                {prediction.confidenceRange.upper.toLocaleString("en-IN")} · {prediction.model} ({prediction.dataPointsUsed} months of data)
              </p>
            </>
          ) : (
            <div className="mt-3 h-12 animate-pulse rounded-lg bg-slate-100" />
          )}
        </div>

        {anomalies.length > 0 && (
          <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5">
            <p className="text-sm font-medium text-amber-800">⚠️ Unusual spending detected</p>
            <div className="mt-2 space-y-1.5">
              {anomalies.slice(0, 5).map((a) => (
                <p key={a.id} className="text-sm text-amber-700">
                  {a.reason}
                </p>
              ))}
            </div>
          </div>
        )}

        {forecasts.length > 0 && (
          <div className="rounded-2xl border border-slate-200 bg-white p-5">
            <p className="text-sm font-medium text-ink-700">Category forecasts</p>
            <div className="mt-3 space-y-2">
              {forecasts.slice(0, 6).map((f) => (
                <div key={f.category} className="flex items-center justify-between text-sm">
                  <span className="text-ink-700">{f.category}</span>
                  <span className="text-ink-500">
                    ₹{f.currentMonth.toLocaleString("en-IN")} so far · projected ₹{f.projected.toLocaleString("en-IN")}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
